### ISSUE TITLE
Handle hauk error condition

### ISSUE THREAD

**Issue by pvagner** [tuffnerdstuff/hauk-snitch#10]
Hello,
When there are issues creating new hauk sessions such as when hauk can't access redis or memcached, the app exits with traceback like this. It would be great if it would be possible to report hauk errors similar to how hauk android app does it.

```2021/06/05 12:04:52 Session for topic owntracks/pvagner/redmi9 does not exist and autostart is disabled
panic: runtime error: index out of range [3] with length 2

goroutine 1 [running]:
github.com/tuffnerdstuff/hauk-snitch/hauk.(*client).CreateSession(0xc000150280, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0006342d8, 0x3)
        /home/pvagner/builds/hauk-snitch/hauk/client.go:51 +0x5e5
github.com/tuffnerdstuff/hauk-snitch/mapper.(*Mapper).createNewSIDForTopic(0xa45dc0, 0xc00063a150, 0x18, 0x1, 0xc000122898, 0x0, 0xffffffffffffffff)
        /home/pvagner/builds/hauk-snitch/mapper/mapper.go:107 +0x73
github.com/tuffnerdstuff/hauk-snitch/mapper.(*Mapper).getOrCreateSID(0xa45dc0, 0xc00063a150, 0x18, 0xc000632450, 0x0, 0x0, 0x862000, 0xc0006462e0)
        /home/pvagner/builds/hauk-snitch/mapper/mapper.go:76 +0x105
github.com/tuffnerdstuff/hauk-snitch/mapper.(*Mapper).Run(0xa45dc0, 0xc0000747e0)
        /home/pvagner/builds/hauk-snitch/mapper/mapper.go:60 +0x179
main.initMapper()
        /home/pvagner/builds/hauk-snitch/main.go:58 +0x125
main.main()
        /home/pvagner/builds/hauk-snitch/main.go:27 +0x23b```

**Comment by tuffnerdstuff** [comment]
Thanks for your suggestion! Do you mean you want to error message to be sent to you via email? That should be doable. If you would like to see the error message in your client (i.e. opentracks app), however, I don't think this is possible.

**Comment by pvagner** [comment]
I have it configured so when I click report in the owntracks app new session is created. I do receive mail with the link.
Sometimes e.g. after upgrading server components it's not possible to create the session. A note to that would be fine. Also the main point is that the app exits when this happens thus it has to be restarted.

**Comment by tuffnerdstuff** [comment]
OK, I'll look into error handling. Meanwhile, if you're using the docker setup you could adapt the restart-policy to your needs. e.g. if you use "on-failure", then the hauk-snitch container restarts after a failure: https://docs.docker.com/config/containers/start-containers-automatically/

**Comment by tuffnerdstuff** [comment]
I'm working on a fix for the particular error right now, I just want to perform some testing first. You're right, hauk-snitch should not exit in that case but ignore the new session. I will also use that opportunity to implement a general error-notification via e-mail.

**Comment by tuffnerdstuff** [comment]
I now validate the response body from Hauk and just skip the session alltogether in case it is invalid. That way hauk-snitch keeps running as it should. You'll also receive an e-mail informing you that the response received from Hauk is malformed. If a different uncaught error occurs in the future hauk-snitch will also send out an e-mail containing the error-message, the stack-trace and the information that hauk-snitch terminated. If you can reproduce your particular redis or memcached problem, please feel free to test the bugfix-branch for this issue before I clean up the fix and merge it in the master branch:
[https://github.com/tuffnerdstuff/hauk-snitch/tree/bugfix/handle-malformed-response](https://github.com/tuffnerdstuff/hauk-snitch/tree/bugfix/handle-malformed-response)
